# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


"""WARNING: This file is generated in a testing context and should not be used in production.
Lines specific to the testing context are marked with a test tube emoji (🧪) to indicate
that they would not be included (or would be different) in the production version of this file.
"""

import os
import warnings  # 🧪
from typing import Any

from ecoscope.platform.tasks.config import set_workflow_details as set_workflow_details
from ecoscope.platform.tasks.filter import set_time_range as set_time_range
from ecoscope.platform.tasks.io import set_er_connection as set_er_connection
from ecoscope.platform.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope.platform.tasks.skip import any_is_empty_df as any_is_empty_df
from wt_contracts import validate as _validate
from wt_task import task
from wt_task.testing import create_func_magicmock  # 🧪

from .. import metadata as _metadata

get_subjectgroup_observations = create_func_magicmock(  # 🧪
    anchor="ecoscope.platform.tasks.io",  # 🧪
    func_name="get_subjectgroup_observations",  # 🧪
)  # 🧪
from ecoscope.platform.tasks.config import get_bounding_box as get_bounding_box
from ecoscope.platform.tasks.config import (
    get_filter_point_coords as get_filter_point_coords,
)
from ecoscope.platform.tasks.config import get_segment_filter as get_segment_filter
from ecoscope.platform.tasks.config import set_traj_filters as set_traj_filters
from ecoscope.platform.tasks.groupby import set_groupers as set_groupers
from ecoscope.platform.tasks.transformation import (
    apply_reloc_coord_filter as apply_reloc_coord_filter,
)
from ecoscope.platform.tasks.transformation import (
    extract_spatial_grouper_feature_group_names as extract_spatial_grouper_feature_group_names,
)

get_spatial_features_group = create_func_magicmock(  # 🧪
    anchor="ecoscope.platform.tasks.io",  # 🧪
    func_name="get_spatial_features_group",  # 🧪
)  # 🧪
from ecoscope.platform.tasks.analysis import (
    generate_bbmm_raster as generate_bbmm_raster,
)
from ecoscope.platform.tasks.config import (
    any_is_non_bbmm_method_args as any_is_non_bbmm_method_args,
)
from ecoscope.platform.tasks.config import (
    any_is_non_etd_method_args as any_is_non_etd_method_args,
)
from ecoscope.platform.tasks.config import (
    call_home_range_from_args as call_home_range_from_args,
)
from ecoscope.platform.tasks.config import (
    get_bbmm_raster_params_from_args as get_bbmm_raster_params_from_args,
)
from ecoscope.platform.tasks.config import (
    get_etd_raster_params_from_args as get_etd_raster_params_from_args,
)
from ecoscope.platform.tasks.config import (
    get_rings_correction_from_args as get_rings_correction_from_args,
)
from ecoscope.platform.tasks.config import (
    get_stroked_from_args as get_stroked_from_args,
)
from ecoscope.platform.tasks.config import (
    relocations_for_points_overlay as relocations_for_points_overlay,
)
from ecoscope.platform.tasks.config import set_home_range_args as set_home_range_args
from ecoscope.platform.tasks.config import set_string_var as set_string_var
from ecoscope.platform.tasks.groupby import groupbykey as groupbykey
from ecoscope.platform.tasks.groupby import split_groups as split_groups
from ecoscope.platform.tasks.io import (
    persist_grouped_dfs_for_results_download as persist_grouped_dfs_for_results_download,
)
from ecoscope.platform.tasks.io import persist_text as persist_text
from ecoscope.platform.tasks.preprocessing import (
    convert_trajectory_to_relocations as convert_trajectory_to_relocations,
)
from ecoscope.platform.tasks.preprocessing import (
    process_relocations as process_relocations,
)
from ecoscope.platform.tasks.preprocessing import (
    relocations_to_trajectory as relocations_to_trajectory,
)
from ecoscope.platform.tasks.results import create_geojson_layer as create_geojson_layer
from ecoscope.platform.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope.platform.tasks.results import (
    create_plot_widget_single_view as create_plot_widget_single_view,
)
from ecoscope.platform.tasks.results import draw_map as draw_map
from ecoscope.platform.tasks.results import draw_table as draw_table
from ecoscope.platform.tasks.results import gather_dashboard as gather_dashboard
from ecoscope.platform.tasks.results import merge_widget_views as merge_widget_views
from ecoscope.platform.tasks.results import set_base_maps as set_base_maps
from ecoscope.platform.tasks.results import set_layer_opacity as set_layer_opacity
from ecoscope.platform.tasks.transformation import (
    add_spatial_index as add_spatial_index,
)
from ecoscope.platform.tasks.transformation import (
    add_temporal_index as add_temporal_index,
)
from ecoscope.platform.tasks.transformation import apply_color_map as apply_color_map
from ecoscope.platform.tasks.transformation import (
    apply_rings_correction_if_enabled as apply_rings_correction_if_enabled,
)
from ecoscope.platform.tasks.transformation import apply_sql_query as apply_sql_query
from ecoscope.platform.tasks.transformation import (
    convert_column_values_to_string as convert_column_values_to_string,
)
from ecoscope.platform.tasks.transformation import convert_crs as convert_crs
from ecoscope.platform.tasks.transformation import map_columns as map_columns
from ecoscope.platform.tasks.transformation import (
    resolve_spatial_feature_groups_for_spatial_groupers as resolve_spatial_feature_groups_for_spatial_groupers,
)
from ecoscope_workflows_ext_custom.tasks.analysis import (
    generate_etd_raster as generate_etd_raster_1,
)
from ecoscope_workflows_ext_custom.tasks.results import (
    compute_fitted_view_state as compute_fitted_view_state,
)


def main(params: dict[str, Any], validate_params_schema: bool = True):
    warnings.warn("This test script should not be used in production!")  # 🧪

    if validate_params_schema:
        _validate(params, _metadata.load_params_schema())

    workflow_details = (
        task(set_workflow_details)
        .validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("workflow_details") or {}))
        .call()
    )

    er_client = (
        task(set_er_connection)
        .validate()
        .set_task_instance_id("er_client")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("er_client") or {}))
        .call()
    )

    time_range = (
        task(set_time_range)
        .validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_format="%d %b %Y", **(params.get("time_range") or {}))
        .call()
    )

    subject_observations = (
        task(get_subjectgroup_observations)
        # 🧪 validation omitted for mocked IO task (returns pre-loaded example data)
        .set_task_instance_id("subject_observations")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            filter="clean",
            client=er_client,
            time_range=time_range,
            raise_on_empty=True,
            include_details=False,
            include_subjectsource_details=False,
            **(params.get("subject_observations") or {}),
        )
        .call()
    )

    subject_filters = (
        task(set_traj_filters)
        .validate()
        .set_task_instance_id("subject_filters")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("subject_filters") or {}))
        .call()
    )

    bounding_box = (
        task(get_bounding_box)
        .validate()
        .set_task_instance_id("bounding_box")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(filters=subject_filters, **(params.get("bounding_box") or {}))
        .call()
    )

    filter_point_coords = (
        task(get_filter_point_coords)
        .validate()
        .set_task_instance_id("filter_point_coords")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(filters=subject_filters, **(params.get("filter_point_coords") or {}))
        .call()
    )

    segment_filter = (
        task(get_segment_filter)
        .validate()
        .set_task_instance_id("segment_filter")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(filters=subject_filters, **(params.get("segment_filter") or {}))
        .call()
    )

    subject_obs_filtered = (
        task(apply_reloc_coord_filter)
        .validate()
        .set_task_instance_id("subject_obs_filtered")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=subject_observations,
            bounding_box=bounding_box,
            filter_point_coords=None,
            roi_gdf=None,
            roi_name=None,
            reset_index=False,
            **(params.get("subject_obs_filtered") or {}),
        )
        .call()
    )

    groupers = (
        task(set_groupers)
        .validate()
        .set_task_instance_id("groupers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("groupers") or {}))
        .call()
    )

    spatial_group_ids = (
        task(extract_spatial_grouper_feature_group_names)
        .validate()
        .set_task_instance_id("spatial_group_ids")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(groupers=groupers, **(params.get("spatial_group_ids") or {}))
        .call()
    )

    fetch_spatial_feature_groups = (
        task(get_spatial_features_group)
        # 🧪 validation omitted for mocked IO task (returns pre-loaded example data)
        .set_task_instance_id("fetch_spatial_feature_groups")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(client=er_client, **(params.get("fetch_spatial_feature_groups") or {}))
        .map(argnames=["spatial_features_group_name"], argvalues=spatial_group_ids)
    )

    resolved_groupers = (
        task(resolve_spatial_feature_groups_for_spatial_groupers)
        .validate()
        .set_task_instance_id("resolved_groupers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            groupers=groupers,
            spatial_feature_groups=fetch_spatial_feature_groups,
            **(params.get("resolved_groupers") or {}),
        )
        .call()
    )

    subject_reloc = (
        task(process_relocations)
        .validate()
        .set_task_instance_id("subject_reloc")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            observations=subject_obs_filtered,
            relocs_columns=[
                "groupby_col",
                "fixtime",
                "junk_status",
                "geometry",
                "extra__subject__name",
                "extra__subject__subject_subtype",
                "extra__subject__sex",
            ],
            filter_point_coords=filter_point_coords,
            **(params.get("subject_reloc") or {}),
        )
        .call()
    )

    subject_traj = (
        task(relocations_to_trajectory)
        .validate()
        .set_task_instance_id("subject_traj")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            relocations=subject_reloc,
            trajectory_segment_filter=segment_filter,
            **(params.get("subject_traj") or {}),
        )
        .call()
    )

    traj_temporal_index = (
        task(add_temporal_index)
        .validate()
        .set_task_instance_id("traj_temporal_index")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=subject_traj,
            time_col="segment_start",
            groupers=resolved_groupers,
            cast_to_datetime=True,
            format="mixed",
            **(params.get("traj_temporal_index") or {}),
        )
        .call()
    )

    traj_spatial_index = (
        task(add_spatial_index)
        .validate()
        .set_task_instance_id("traj_spatial_index")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            gdf=traj_temporal_index,
            groupers=resolved_groupers,
            **(params.get("traj_spatial_index") or {}),
        )
        .call()
    )

    subject_traj_named = (
        task(map_columns)
        .validate()
        .set_task_instance_id("subject_traj_named")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=traj_spatial_index,
            drop_columns=[],
            retain_columns=[],
            rename_columns={
                "extra__name": "subject_name",
                "extra__subject_subtype": "subject_subtype",
                "extra__sex": "subject_sex",
            },
            raise_if_not_found=True,
            **(params.get("subject_traj_named") or {}),
        )
        .call()
    )

    subject_traj_groups = (
        task(split_groups)
        .validate()
        .set_task_instance_id("subject_traj_groups")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=subject_traj_named,
            groupers=resolved_groupers,
            **(params.get("subject_traj_groups") or {}),
        )
        .call()
    )

    base_map_defs = (
        task(set_base_maps)
        .validate()
        .set_task_instance_id("base_map_defs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("base_map_defs") or {}))
        .call()
    )

    home_range_args = (
        task(set_home_range_args)
        .validate()
        .set_task_instance_id("home_range_args")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("home_range_args") or {}))
        .call()
    )

    etd_raster_params = (
        task(get_etd_raster_params_from_args)
        .validate()
        .set_task_instance_id("etd_raster_params")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
                any_is_non_etd_method_args,
            ],
            unpack_depth=1,
        )
        .partial(args=home_range_args, **(params.get("etd_raster_params") or {}))
        .call()
    )

    etd_raster = (
        task(generate_etd_raster_1)
        .validate()
        .set_task_instance_id("etd_raster")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            combined_params=etd_raster_params,
            filename="etd_home_range_raster",
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            **(params.get("etd_raster") or {}),
        )
        .map(argnames=["group_key", "trajectory_gdf"], argvalues=subject_traj_groups)
    )

    bbmm_raster_params = (
        task(get_bbmm_raster_params_from_args)
        .validate()
        .set_task_instance_id("bbmm_raster_params")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
                any_is_non_bbmm_method_args,
            ],
            unpack_depth=1,
        )
        .partial(args=home_range_args, **(params.get("bbmm_raster_params") or {}))
        .call()
    )

    bbmm_raster = (
        task(generate_bbmm_raster)
        .validate()
        .set_task_instance_id("bbmm_raster")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            combined_params=bbmm_raster_params,
            filename="bbmm_home_range_raster",
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            **(params.get("bbmm_raster") or {}),
        )
        .map(argnames=["group_key", "trajectory_gdf"], argvalues=subject_traj_groups)
    )

    subject_reloc_groups = (
        task(convert_trajectory_to_relocations)
        .validate()
        .set_task_instance_id("subject_reloc_groups")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("subject_reloc_groups") or {}))
        .mapvalues(argnames=["trajectory_gdf"], argvalues=subject_traj_groups)
    )

    home_range_percentiles_grouped = (
        task(call_home_range_from_args)
        .validate()
        .set_task_instance_id("home_range_percentiles_grouped")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            args=home_range_args, **(params.get("home_range_percentiles_grouped") or {})
        )
        .mapvalues(argnames=["trajectory_gdf"], argvalues=subject_traj_groups)
    )

    home_range_legend_title = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("home_range_legend_title")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("home_range_legend_title") or {}))
        .call()
    )

    home_range_opacity = (
        task(set_layer_opacity)
        .validate()
        .set_task_instance_id("home_range_opacity")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("home_range_opacity") or {}))
        .call()
    )

    home_range_stroked = (
        task(get_stroked_from_args)
        .validate()
        .set_task_instance_id("home_range_stroked")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(args=home_range_args, **(params.get("home_range_stroked") or {}))
        .call()
    )

    home_range_rings_correction = (
        task(get_rings_correction_from_args)
        .validate()
        .set_task_instance_id("home_range_rings_correction")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            args=home_range_args, **(params.get("home_range_rings_correction") or {})
        )
        .call()
    )

    home_range_points_gdf = (
        task(relocations_for_points_overlay)
        .validate()
        .set_task_instance_id("home_range_points_gdf")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(args=home_range_args, **(params.get("home_range_points_gdf") or {}))
        .mapvalues(argnames=["relocations_gdf"], argvalues=subject_reloc_groups)
    )

    home_range_points_wgs84 = (
        task(convert_crs)
        .validate()
        .set_task_instance_id("home_range_points_wgs84")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(crs="EPSG:4326", **(params.get("home_range_points_wgs84") or {}))
        .mapvalues(argnames=["df"], argvalues=home_range_points_gdf)
    )

    home_range_points_layer = (
        task(create_geojson_layer)
        .validate()
        .set_task_instance_id("home_range_points_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            layer_style={
                "filled": True,
                "stroked": True,
                "get_fill_color": [0, 0, 0],
                "get_line_color": [0, 0, 0],
                "get_line_width": 0,
                "get_point_radius": 1.5,
                "point_radius_units": "pixels",
                "point_radius_min_pixels": 1,
                "opacity": 0.8,
            },
            legend=None,
            tooltip_columns=["fixtime"],
            zoom=False,
            data_url=None,
            **(params.get("home_range_points_layer") or {}),
        )
        .mapvalues(argnames=["geodataframe"], argvalues=home_range_points_wgs84)
    )

    persist_home_range_pct_grouped = (
        task(persist_grouped_dfs_for_results_download)
        .validate()
        .set_task_instance_id("persist_home_range_pct_grouped")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            grouped_dfs=home_range_percentiles_grouped,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_prefix="home_range_percentiles",
            sanitize=False,
            **(params.get("persist_home_range_pct_grouped") or {}),
        )
        .call()
    )

    home_range_pct_rings = (
        task(apply_rings_correction_if_enabled)
        .validate()
        .set_task_instance_id("home_range_pct_rings")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            enabled=home_range_rings_correction,
            **(params.get("home_range_pct_rings") or {}),
        )
        .mapvalues(
            argnames=["percentiles_gdf"], argvalues=home_range_percentiles_grouped
        )
    )

    home_range_pct_to_string = (
        task(convert_column_values_to_string)
        .validate()
        .set_task_instance_id("home_range_pct_to_string")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            columns=["percentile"], **(params.get("home_range_pct_to_string") or {})
        )
        .mapvalues(argnames=["df"], argvalues=home_range_pct_rings)
    )

    home_range_pct_colormap = (
        task(apply_color_map)
        .validate()
        .set_task_instance_id("home_range_pct_colormap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            input_column_name="percentile",
            colormap="RdYlGn_r",
            output_column_name="percentile_color",
            **(params.get("home_range_pct_colormap") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=home_range_pct_to_string)
    )

    home_range_pct_wgs84 = (
        task(convert_crs)
        .validate()
        .set_task_instance_id("home_range_pct_wgs84")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(crs="EPSG:4326", **(params.get("home_range_pct_wgs84") or {}))
        .mapvalues(argnames=["df"], argvalues=home_range_pct_colormap)
    )

    home_range_pct_display = (
        task(map_columns)
        .validate()
        .set_task_instance_id("home_range_pct_display")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            drop_columns=[],
            retain_columns=[],
            rename_columns={"percentile": "Percentile", "area_sqkm": "Area (km²)"},
            raise_if_not_found=True,
            **(params.get("home_range_pct_display") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=home_range_pct_wgs84)
    )

    home_range_pct_layer = (
        task(create_geojson_layer)
        .validate()
        .set_task_instance_id("home_range_pct_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            layer_style={
                "filled": True,
                "stroked": home_range_stroked,
                "get_fill_color": "percentile_color",
                "get_line_color": [0, 0, 0],
                "get_line_width": 2,
                "opacity": home_range_opacity,
            },
            legend={
                "title": home_range_legend_title,
                "label_column": "Percentile",
                "label_suffix": " %",
                "color_column": "percentile_color",
                "sort": "ascending",
            },
            tooltip_columns=["Percentile", "Area (km²)"],
            zoom=False,
            data_url=None,
            **(params.get("home_range_pct_layer") or {}),
        )
        .mapvalues(argnames=["geodataframe"], argvalues=home_range_pct_display)
    )

    home_range_combined_layers = (
        task(groupbykey)
        .validate()
        .set_task_instance_id("home_range_combined_layers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            iterables=[home_range_pct_layer, home_range_points_layer],
            **(params.get("home_range_combined_layers") or {}),
        )
        .call()
    )

    home_range_view_state = (
        task(compute_fitted_view_state)
        .validate()
        .set_task_instance_id("home_range_view_state")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(max_zoom=15, **(params.get("home_range_view_state") or {}))
        .mapvalues(argnames=["geo_layers"], argvalues=home_range_combined_layers)
    )

    home_range_map_and_view = (
        task(groupbykey)
        .validate()
        .set_task_instance_id("home_range_map_and_view")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            iterables=[home_range_combined_layers, home_range_view_state],
            **(params.get("home_range_map_and_view") or {}),
        )
        .call()
    )

    home_range_map = (
        task(draw_map)
        .validate()
        .set_task_instance_id("home_range_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            tile_layers=base_map_defs,
            static=False,
            title=None,
            output_type="html",
            max_zoom=15,
            legend_style={"placement": "bottom-right"},
            **(params.get("home_range_map") or {}),
        )
        .mapvalues(
            argnames=["geo_layers", "view_state"], argvalues=home_range_map_and_view
        )
    )

    persist_home_range_map_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("persist_home_range_map_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="home_range_map",
            **(params.get("persist_home_range_map_html") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=home_range_map)
    )

    home_range_map_widget_views = (
        task(create_map_widget_single_view)
        .validate()
        .set_task_instance_id("home_range_map_widget_views")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Home Range Map", **(params.get("home_range_map_widget_views") or {})
        )
        .map(argnames=["view", "data"], argvalues=persist_home_range_map_html)
    )

    home_range_map_widget = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("home_range_map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            widgets=home_range_map_widget_views,
            **(params.get("home_range_map_widget") or {}),
        )
        .call()
    )

    home_range_pct_table_columns = (
        task(apply_sql_query)
        .validate()
        .set_task_instance_id("home_range_pct_table_columns")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            query='SELECT "Percentile", ROUND("Area (km²)", 2) AS "Area (km²)" FROM df',
            columns=["Percentile", "Area (km²)"],
            sanitize=True,
            **(params.get("home_range_pct_table_columns") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=home_range_pct_display)
    )

    home_range_pct_table = (
        task(draw_table)
        .validate()
        .set_task_instance_id("home_range_pct_table")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            columns=None,
            table_config={
                "enable_sorting": True,
                "enable_filtering": True,
                "enable_download": True,
                "hide_header": False,
            },
            **(params.get("home_range_pct_table") or {}),
        )
        .mapvalues(argnames=["dataframe"], argvalues=home_range_pct_table_columns)
    )

    persist_home_range_table_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("persist_home_range_table_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="home_range_percentile_table",
            **(params.get("persist_home_range_table_html") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=home_range_pct_table)
    )

    home_range_table_widget_views = (
        task(create_plot_widget_single_view)
        .validate()
        .set_task_instance_id("home_range_table_widget_views")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Percentile Table",
            **(params.get("home_range_table_widget_views") or {}),
        )
        .map(argnames=["view", "data"], argvalues=persist_home_range_table_html)
    )

    home_range_pct_table_widget = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("home_range_pct_table_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            widgets=home_range_table_widget_views,
            **(params.get("home_range_pct_table_widget") or {}),
        )
        .call()
    )

    dashboard = (
        task(gather_dashboard)
        .validate()
        .set_task_instance_id("dashboard")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            details=workflow_details,
            widgets=[home_range_map_widget, home_range_pct_table_widget],
            groupers=resolved_groupers,
            time_range=time_range,
            **(params.get("dashboard") or {}),
        )
        .call()
    )

    return dashboard
