# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details

# ruff: noqa: E402

"""WARNING: This file is generated in a testing context and should not be used in production.
Lines specific to the testing context are marked with a test tube emoji (🧪) to indicate
that they would not be included (or would be different) in the production version of this file.
"""

import os
import warnings  # 🧪
from typing import Any

from ecoscope.platform.tasks.config import set_workflow_details as set_workflow_details
from ecoscope.platform.tasks.filter import set_time_range as set_time_range
from ecoscope.platform.tasks.io import set_er_connection as set_er_connection
from ecoscope.platform.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope.platform.tasks.skip import any_is_empty_df as any_is_empty_df
from wt_contracts import validate as _validate
from wt_task import task
from wt_task.testing import create_func_magicmock  # 🧪

from .. import metadata as _metadata

get_subjectgroup_observations = create_func_magicmock(  # 🧪
    anchor="ecoscope.platform.tasks.io",  # 🧪
    func_name="get_subjectgroup_observations",  # 🧪
)  # 🧪
from ecoscope.platform.tasks.groupby import set_groupers as set_groupers
from ecoscope.platform.tasks.transformation import (
    extract_spatial_grouper_feature_group_names as extract_spatial_grouper_feature_group_names,
)

get_spatial_features_group = create_func_magicmock(  # 🧪
    anchor="ecoscope.platform.tasks.io",  # 🧪
    func_name="get_spatial_features_group",  # 🧪
)  # 🧪
from ecoscope.platform.tasks.config import (
    call_etd_from_combined_params as call_etd_from_combined_params,
)
from ecoscope.platform.tasks.config import (
    get_opacity_from_combined_params as get_opacity_from_combined_params,
)
from ecoscope.platform.tasks.config import (
    set_etd_args_with_opacity as set_etd_args_with_opacity,
)
from ecoscope.platform.tasks.groupby import merge_df as merge_df
from ecoscope.platform.tasks.groupby import split_groups as split_groups
from ecoscope.platform.tasks.io import persist_df as persist_df
from ecoscope.platform.tasks.io import persist_text as persist_text
from ecoscope.platform.tasks.preprocessing import (
    process_relocations as process_relocations,
)
from ecoscope.platform.tasks.preprocessing import (
    relocations_to_trajectory as relocations_to_trajectory,
)
from ecoscope.platform.tasks.results import create_geojson_layer as create_geojson_layer
from ecoscope.platform.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope.platform.tasks.results import (
    create_plot_widget_single_view as create_plot_widget_single_view,
)
from ecoscope.platform.tasks.results import draw_map as draw_map
from ecoscope.platform.tasks.results import draw_table as draw_table
from ecoscope.platform.tasks.results import gather_dashboard as gather_dashboard
from ecoscope.platform.tasks.results import merge_widget_views as merge_widget_views
from ecoscope.platform.tasks.results import set_base_maps as set_base_maps
from ecoscope.platform.tasks.transformation import (
    add_spatial_index as add_spatial_index,
)
from ecoscope.platform.tasks.transformation import (
    add_temporal_index as add_temporal_index,
)
from ecoscope.platform.tasks.transformation import apply_color_map as apply_color_map
from ecoscope.platform.tasks.transformation import (
    convert_column_values_to_string as convert_column_values_to_string,
)
from ecoscope.platform.tasks.transformation import convert_crs as convert_crs
from ecoscope.platform.tasks.transformation import map_columns as map_columns
from ecoscope.platform.tasks.transformation import (
    map_values_with_unit as map_values_with_unit,
)
from ecoscope.platform.tasks.transformation import (
    resolve_spatial_feature_groups_for_spatial_groupers as resolve_spatial_feature_groups_for_spatial_groupers,
)
from ecoscope_workflows_ext_custom.tasks.io import (
    persist_grouped_dfs_for_results_download as persist_grouped_dfs_for_results_download,
)
from ecoscope_workflows_ext_wd.tasks import generate_etd_raster as generate_etd_raster


def main(params: dict[str, Any], validate_params_schema: bool = True):
    warnings.warn("This test script should not be used in production!")  # 🧪

    if validate_params_schema:
        _validate(params, _metadata.load_params_schema())

    workflow_details = (
        task(set_workflow_details)
        .validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("workflow_details") or {}))
        .call()
    )

    er_client = (
        task(set_er_connection)
        .validate()
        .set_task_instance_id("er_client")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("er_client") or {}))
        .call()
    )

    time_range = (
        task(set_time_range)
        .validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_format="%d %b %Y", **(params.get("time_range") or {}))
        .call()
    )

    subject_observations = (
        task(get_subjectgroup_observations)
        # 🧪 validation omitted for mocked IO task (returns pre-loaded example data)
        .set_task_instance_id("subject_observations")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            filter="clean",
            client=er_client,
            time_range=time_range,
            raise_on_empty=True,
            include_details=False,
            include_subjectsource_details=False,
            **(params.get("subject_observations") or {}),
        )
        .call()
    )

    groupers = (
        task(set_groupers)
        .validate()
        .set_task_instance_id("groupers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("groupers") or {}))
        .call()
    )

    spatial_group_ids = (
        task(extract_spatial_grouper_feature_group_names)
        .validate()
        .set_task_instance_id("spatial_group_ids")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(groupers=groupers, **(params.get("spatial_group_ids") or {}))
        .call()
    )

    fetch_spatial_feature_groups = (
        task(get_spatial_features_group)
        # 🧪 validation omitted for mocked IO task (returns pre-loaded example data)
        .set_task_instance_id("fetch_spatial_feature_groups")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(client=er_client, **(params.get("fetch_spatial_feature_groups") or {}))
        .map(argnames=["spatial_features_group_name"], argvalues=spatial_group_ids)
    )

    resolved_groupers = (
        task(resolve_spatial_feature_groups_for_spatial_groupers)
        .validate()
        .set_task_instance_id("resolved_groupers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            groupers=groupers,
            spatial_feature_groups=fetch_spatial_feature_groups,
            **(params.get("resolved_groupers") or {}),
        )
        .call()
    )

    subject_reloc = (
        task(process_relocations)
        .validate()
        .set_task_instance_id("subject_reloc")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            observations=subject_observations,
            relocs_columns=[
                "groupby_col",
                "fixtime",
                "junk_status",
                "geometry",
                "extra__subject__name",
                "extra__subject__subject_subtype",
                "extra__subject__sex",
            ],
            filter_point_coords=[
                {"x": 180.0, "y": 90.0},
                {"x": 0.0, "y": 0.0},
                {"x": 1.0, "y": 1.0},
            ],
            **(params.get("subject_reloc") or {}),
        )
        .call()
    )

    subject_traj = (
        task(relocations_to_trajectory)
        .validate()
        .set_task_instance_id("subject_traj")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(relocations=subject_reloc, **(params.get("subject_traj") or {}))
        .call()
    )

    traj_temporal_index = (
        task(add_temporal_index)
        .validate()
        .set_task_instance_id("traj_temporal_index")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=subject_traj,
            time_col="segment_start",
            groupers=resolved_groupers,
            cast_to_datetime=True,
            format="mixed",
            **(params.get("traj_temporal_index") or {}),
        )
        .call()
    )

    traj_spatial_index = (
        task(add_spatial_index)
        .validate()
        .set_task_instance_id("traj_spatial_index")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            gdf=traj_temporal_index,
            groupers=resolved_groupers,
            **(params.get("traj_spatial_index") or {}),
        )
        .call()
    )

    subject_traj_named = (
        task(map_columns)
        .validate()
        .set_task_instance_id("subject_traj_named")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=traj_spatial_index,
            drop_columns=[],
            retain_columns=[],
            rename_columns={
                "extra__name": "subject_name",
                "extra__subject_subtype": "subject_subtype",
                "extra__sex": "subject_sex",
            },
            raise_if_not_found=True,
            **(params.get("subject_traj_named") or {}),
        )
        .call()
    )

    subject_traj_groups = (
        task(split_groups)
        .validate()
        .set_task_instance_id("subject_traj_groups")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=subject_traj_named,
            groupers=resolved_groupers,
            **(params.get("subject_traj_groups") or {}),
        )
        .call()
    )

    base_map_defs = (
        task(set_base_maps)
        .validate()
        .set_task_instance_id("base_map_defs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("base_map_defs") or {}))
        .call()
    )

    etd_args = (
        task(set_etd_args_with_opacity)
        .validate()
        .set_task_instance_id("etd_args")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(nodata_value="nan", band_count=1, **(params.get("etd_args") or {}))
        .call()
    )

    etd_opacity = (
        task(get_opacity_from_combined_params)
        .validate()
        .set_task_instance_id("etd_opacity")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(combined_params=etd_args, **(params.get("etd_opacity") or {}))
        .call()
    )

    etd_percentiles_grouped = (
        task(call_etd_from_combined_params)
        .validate()
        .set_task_instance_id("etd_percentiles_grouped")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            combined_params=etd_args, **(params.get("etd_percentiles_grouped") or {})
        )
        .mapvalues(argnames=["trajectory_gdf"], argvalues=subject_traj_groups)
    )

    etd_percentiles = (
        task(merge_df)
        .validate()
        .set_task_instance_id("etd_percentiles")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            iterables=etd_percentiles_grouped, **(params.get("etd_percentiles") or {})
        )
        .call()
    )

    persist_etd_pct_geoparquet = (
        task(persist_df)
        .validate()
        .set_task_instance_id("persist_etd_pct_geoparquet")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetype="geoparquet",
            filename="etd_home_range_percentiles",
            df=etd_percentiles,
            **(params.get("persist_etd_pct_geoparquet") or {}),
        )
        .call()
    )

    persist_etd_pct_csv = (
        task(persist_df)
        .validate()
        .set_task_instance_id("persist_etd_pct_csv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetype="csv",
            filename="etd_home_range_percentiles",
            df=etd_percentiles,
            **(params.get("persist_etd_pct_csv") or {}),
        )
        .call()
    )

    etd_raster = (
        task(generate_etd_raster)
        .validate()
        .set_task_instance_id("etd_raster")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            combined_params=etd_args,
            filename="etd_home_range_raster",
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            **(params.get("etd_raster") or {}),
        )
        .map(argnames=["group_key", "trajectory_gdf"], argvalues=subject_traj_groups)
    )

    persist_etd_pct_grouped = (
        task(persist_grouped_dfs_for_results_download)
        .validate()
        .set_task_instance_id("persist_etd_pct_grouped")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            grouped_dfs=etd_percentiles_grouped,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_prefix="etd_home_range_percentiles",
            sanitize=False,
            **(params.get("persist_etd_pct_grouped") or {}),
        )
        .call()
    )

    etd_pct_to_string = (
        task(convert_column_values_to_string)
        .validate()
        .set_task_instance_id("etd_pct_to_string")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(columns=["percentile"], **(params.get("etd_pct_to_string") or {}))
        .mapvalues(argnames=["df"], argvalues=etd_percentiles_grouped)
    )

    etd_pct_colormap = (
        task(apply_color_map)
        .validate()
        .set_task_instance_id("etd_pct_colormap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            input_column_name="percentile",
            colormap="RdYlGn_r",
            output_column_name="percentile_color",
            **(params.get("etd_pct_colormap") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=etd_pct_to_string)
    )

    etd_pct_wgs84 = (
        task(convert_crs)
        .validate()
        .set_task_instance_id("etd_pct_wgs84")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(crs="EPSG:4326", **(params.get("etd_pct_wgs84") or {}))
        .mapvalues(argnames=["df"], argvalues=etd_pct_colormap)
    )

    etd_pct_area_display = (
        task(map_values_with_unit)
        .validate()
        .set_task_instance_id("etd_pct_area_display")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            input_column_name="area_sqkm",
            output_column_name="area_sqkm",
            original_unit="km²",
            new_unit="km²",
            decimal_places=2,
            **(params.get("etd_pct_area_display") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=etd_pct_wgs84)
    )

    etd_pct_display = (
        task(map_columns)
        .validate()
        .set_task_instance_id("etd_pct_display")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            drop_columns=[],
            retain_columns=[],
            rename_columns={"percentile": "Percentile", "area_sqkm": "Area"},
            raise_if_not_found=True,
            **(params.get("etd_pct_display") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=etd_pct_area_display)
    )

    etd_pct_layer = (
        task(create_geojson_layer)
        .validate()
        .set_task_instance_id("etd_pct_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            layer_style={
                "filled": True,
                "stroked": False,
                "get_fill_color": "percentile_color",
                "get_line_color": "percentile_color",
                "get_line_width": 0,
                "opacity": etd_opacity,
            },
            legend={
                "title": "Home Range Percentiles",
                "label_column": "Percentile",
                "label_suffix": " %",
                "color_column": "percentile_color",
                "sort": "ascending",
            },
            tooltip_columns=["Percentile", "Area"],
            zoom=True,
            data_url=None,
            **(params.get("etd_pct_layer") or {}),
        )
        .mapvalues(argnames=["geodataframe"], argvalues=etd_pct_display)
    )

    etd_map = (
        task(draw_map)
        .validate()
        .set_task_instance_id("etd_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            tile_layers=base_map_defs,
            static=False,
            title=None,
            output_type="html",
            view_state=None,
            max_zoom=15,
            legend_style={"placement": "bottom-right"},
            **(params.get("etd_map") or {}),
        )
        .mapvalues(argnames=["geo_layers"], argvalues=etd_pct_layer)
    )

    persist_etd_map_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("persist_etd_map_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="etd_home_range_map",
            **(params.get("persist_etd_map_html") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=etd_map)
    )

    etd_map_widget_views = (
        task(create_map_widget_single_view)
        .validate()
        .set_task_instance_id("etd_map_widget_views")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title="ETD Home Range Map", **(params.get("etd_map_widget_views") or {})
        )
        .map(argnames=["view", "data"], argvalues=persist_etd_map_html)
    )

    etd_map_widget = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("etd_map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(widgets=etd_map_widget_views, **(params.get("etd_map_widget") or {}))
        .call()
    )

    etd_pct_table_columns = (
        task(map_columns)
        .validate()
        .set_task_instance_id("etd_pct_table_columns")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            drop_columns=[],
            retain_columns=["Percentile", "Area"],
            rename_columns={},
            raise_if_not_found=True,
            **(params.get("etd_pct_table_columns") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=etd_pct_display)
    )

    etd_pct_table = (
        task(draw_table)
        .validate()
        .set_task_instance_id("etd_pct_table")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("etd_pct_table") or {}))
        .mapvalues(argnames=["dataframe"], argvalues=etd_pct_table_columns)
    )

    persist_etd_pct_table_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("persist_etd_pct_table_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="etd_percentile_table",
            **(params.get("persist_etd_pct_table_html") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=etd_pct_table)
    )

    etd_pct_table_widget_views = (
        task(create_plot_widget_single_view)
        .validate()
        .set_task_instance_id("etd_pct_table_widget_views")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title="ETD Percentile Table",
            **(params.get("etd_pct_table_widget_views") or {}),
        )
        .map(argnames=["view", "data"], argvalues=persist_etd_pct_table_html)
    )

    etd_pct_table_widget = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("etd_pct_table_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            widgets=etd_pct_table_widget_views,
            **(params.get("etd_pct_table_widget") or {}),
        )
        .call()
    )

    dashboard = (
        task(gather_dashboard)
        .validate()
        .set_task_instance_id("dashboard")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            details=workflow_details,
            widgets=[etd_map_widget, etd_pct_table_widget],
            groupers=resolved_groupers,
            time_range=time_range,
            **(params.get("dashboard") or {}),
        )
        .call()
    )

    return dashboard
